const employeeFormConfig = [
    {
        name: "last_name",
        label: "Last Name",
        type: "text",
    },
    {
        name: "first_name",
        label: "First Name",
        type: "text",
    },
    {
        name: "middle_name",
        label: "Middle Name",
        type: "text",
    },
    {
        name: "email",
        label: "Email",
        type: "email",
    },
    {
        name: "address",
        label: "Address",
        type: "text",
    },
    {
        name: "birthdate",
        label: "Birthdate",
        type: "date",
        inputFormat: "MMMM dd, yyyy",
    },
    {
        name: "contact_number",
        label: "Contact Number",
        type: "text",
        inputProps: {
            pattern: "[0-9]{10,15}",
            placeholder: "Enter contact number",
        },
    },
    {
        name: "position",
        label: "Positions",
        type: "select",
        options: [
            { value: "Virtual Professional", label: "Virtual Professional" },
            { value: "Virtual Professional - Supervisor", label: "Virtual Professional - Supervisor" },
            { value: "Admin Asst", label: "Admin Asst" },
            { value: "Admin Asst / Maintenance", label: "Admin Asst / Maintenance" },
            { value: "Accounting Assoc", label: "Accounting Assoc" },
            { value: "Senior Accountant", label: "Senior Accountant" },
            { value: "Recruitment Head/Coordinator", label: "Recruitment Head/Coordinator" },
            { value: "Reports Analyst", label: "Reports Analyst" },
            { value: "HR Manager", label: "HR Manager" },
            { value: "Director of Operations", label: "Director of Operations" },
            { value: "Managing Director", label: "Managing Director" },
            { value: "CEO", label: "CEO" },
            { value: "COO", label: "COO" },
            { value: "IT and Web Dev", label: "IT and Web Dev" },
            { value: "Junior Web Developer", label: "Junior Web Developer" },
            { value: "Office Manager", label: "Office Manager" },
            { value: "Video Editor", label: "Video Editor" },
            { value: "Video and Podcast Editor", label: "Video and Podcast Editor" },
            { value: "Maintenance", label: "Maintenance" },
        ],
    },
    {
        name: "employment_date",
        label: "Employment Date",
        type: "date",
        inputFormat: "MMMM dd, yyyy",
    },
    {
        key: 'user_photo',
        type: 'file',
        label: 'Employee Photo',
        accept: 'image/*',
        helperText: 'Upload a photo (JPEG, PNG, GIF) max 2MB',
        fullWidth: true
    },
    {
        name: "employment_type",
        label: "Employment Type",
        type: "select",
        options: [
            { value: "Regular", label: "Regular" },
            { value: "Probationary", label: "Probationary" },
            { value: "Contractual", label: "Contractual" },
            { value: "Independent Contractor", label: "Independent Contractor" },
        ],
    },
    {
        name: "type",
        label: "Job Type",
        type: "select",
        options: [
            { value: "Full Time", label: "Full Time" },
            { value: "Part Time", label: "Part Time" },
        ],
    },
    {
        name: "work_arrangement",
        label: "Work Arrangement",
        type: "select",
        options: [
            { value: "Home-based", label: "Home-based" },
            { value: "Office-based", label: "Office-based" },
            { value: "Hybrid", label: "Hybrid" },
        ],
    },
    {
        name: "department",
        label: "Department",
        type: "select",
        options: [
            { value: "OPERATIONS", label: "OPERATIONS" },
            { value: "HR", label: "HR" },
            { value: "IT & DEVELOPMENT", label: "IT & DEVELOPMENT" },
            { value: "E20 CREATIVES", label: "E20 CREATIVES" },
            { value: "ACCOUNTING & FINANCE", label: "ACCOUNTING & FINANCE" },
        ],
    },
    {
        name: "team",
        label: "Team",
        type: "select",
        options: [
            { value: "ADMIN", label: "ADMIN" },
            { value: "AJ SOLAR", label: "AJ SOLAR" },
            { value: "CAPRI", label: "CAPRI" },
            { value: "COPRA", label: "COPRA" },
            { value: "HAMBLETON", label: "HAMBLETON" },
            { value: "KRAMER", label: "KRAMER" },
            { value: "MAINE STANDARD BIOFUEL", label: "MAINE STANDARD BIOFUEL" },
            { value: "NONE", label: "NONE" },
            { value: "TRAINING", label: "TRAINING" },
            { value: "TSM", label: "TSM" },
        ],
    },
    {
        name: "contract_hours",
        label: "Contract Hours",
        type: "text",
    },
    {
        name: "status",
        label: "Employment Status",
        type: "select",
        options: [
            { value: "Active", label: "Active" },
            { value: "AWOL", label: "AWOL (Absent without On-Leave)" },
            { value: "Floating", label: "Floating" },
            { value: "New Hired", label: "New Hired" },
            { value: "Resigned", label: "Resigned" },
            { value: "Probation", label: "Probation" },
            { value: "Training", label: "Training" },
            { value: "Terminated", label: "Terminated Contract" },
        ],
    },
    {
        name: "time_in",
        label: "Time-In",
        type: "time-picker",
    },
    {
        name: "time_out",
        label: "Time-Out",
        type: "time-picker",
        readOnly: true,
    },
    {
        name: "hourly_rate",
        label: "Hourly Rate",
        type: "text",
        inputProps: {
            pattern: "[0-9]*",
        },
    },
    {
        name: "daily_rate",
        label: "Daily Rate",
        type: "number",
        inputProps: {
            pattern: "[0-9]*",
            readOnly: true,
        },
    },
];

export default employeeFormConfig;
